from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone


class Message(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    date = models.DateTimeField(default=timezone.now)
    text = models.TextField()
    # Message.id field auto-generated by Django, will be used down the road but no need to define it
    category = models.ManyToManyField(Category, blank=True)

    @classmethod
    def addMessage(cls, user, category, text):
        newMessage = Message.objects.create()
        newMessage.user = user
        newMessage.category = category
        newMessage.text = text
        newMessage.date = timezone.now
        newMessage.save()
        return newMessage

    @classmethod
    def deleteMessage(cls, messageID):
        Message.objects.filter(id=messageID).delete()
        pass

    def editMessage(self, text):
        self.text = text
        self.save()
        pass


class Category(models.Model):
    name = models.TextField(max_length=50)
    message = models.ManyToManyField(Message, blank=True)
    # Category.id field auto-generated by Django, will not be used

