# Generated by Django 3.1.4 on 2020-12-15 13:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=50)),
                ('credinitials', models.IntegerField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.IntegerField(max_length=3)),
                ('semester', models.CharField(choices=[('A', 'Winter'), ('B', 'Spring'),
                                              ('C', 'Summer')], max_length=1)),
                ('year', models.IntegerField(max_length=4)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='grades.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_student',
                                           to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
