# Generated by Django 3.1.4 on 2020-12-19 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='credinitials',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='grade',
            name='grade',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='grade',
            name='year',
            field=models.IntegerField(default=0),
        ),
    ]
