# Generated by Django 3.1.4 on 2020-12-11 12:38

from django.db import migrations, transaction
from django.utils import timezone
from django.contrib.auth.models import User


class Migration(migrations.Migration):

    dependencies = [
        ('forumMessages', '0001_initial'),
    ]

    def generate_data(apps, schema_editor):
        from forumMessages.models import Message, Category

        category_test_data = [
            'General_Discussions',
            'Course_Related',
            'Palavra',
        ]
        with transaction.atomic():
            for name in category_test_data:
                Category(name=name).save()

        user1 = User.objects.create_user(username='Ido2', password='123456789')
        user2 = User.objects.create_user(username='Amit2', password='12345')
        category1 = Category.objects.create(name='Course_Related')
        category2 = Category.objects.create(name='General_discussions')
        message_test_data = [
            (user1, timezone.now, 'Lorem ipsum', category1),
            (user2, timezone.now, 'Dolor sit amet',category2),
        ]
        with transaction.atomic():
            for user, date, text, category in message_test_data:
                msg = Message(user=user, text=text)
                msg.save()
                msg.categories.add(category)


    operations = [
        migrations.RunPython(generate_data)
    ]
